name: flutter_facebook_auth
description: The easiest way to add facebook login to your flutter app. Feature includes getting user information, profile picture and more. This plugin also supports Web.
version: 5.0.0-dev.4
homepage: https://github.com/darwin-morocho/flutter-facebook-auth

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_facebook_auth_platform_interface: ^4.0.1
  # flutter_facebook_auth_platform_interface:
  #   path: ../facebook_auth_platform_interface
  flutter_facebook_auth_web: ^4.0.1
  # flutter_facebook_auth_web:
  #   path: ../facebook_auth_web

  facebook_auth_desktop: ^0.0.3
    # path: ../facebook_auth_desktop

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: app.meedu.flutter_facebook_auth
        pluginClass: FlutterFacebookAuthPlugin
      ios:
        pluginClass: FlutterFacebookAuthPlugin
      web:
        default_package: flutter_facebook_auth_web
      macos:
        default_package: facebook_auth_desktop


