name: flutter_facebook_auth
description: The easiest way to add facebook login to your flutter app, get user information, profile picture and more. Web support included.
version: 3.3.2-no-nullsafety
homepage: https://github.com/darwin-morocho/flutter-facebook-auth

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4
  flutter_facebook_auth_platform_interface: ^2.4.0-no-nullsafety
  # flutter_facebook_auth_platform_interface:
  #   path: ../facebook_auth_platform_interface
  flutter_facebook_auth_web: ^2.4.1-no-nullsafety
  # flutter_facebook_auth_web:
  #   path: ../facebook_auth_web

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: app.meedu.flutter_facebook_auth
        pluginClass: FlutterFacebookAuthPlugin
      ios:
        pluginClass: FlutterFacebookAuthPlugin
      web:
        default_package: flutter_facebook_auth_web
