name: flutter_facebook_auth_web
description: web support for flutter_facebook_auth
version: 2.4.1-no-nullsafety
homepage: https://github.com/darwin-morocho/flutter-facebook-auth/tree/master/facebook_auth_web

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.2
  meta: ^1.2.4
  flutter_facebook_auth_platform_interface: ^2.4.0-no-nullsafety
  # flutter_facebook_auth_platform_interface:
  #   path: ../facebook_auth_platform_interface
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterFacebookAuthPlugin
        fileName: flutter_facebook_auth_web.dart
