name: facebook_auth_desktop
description: macOS support for flutter_facebook_auth
version: 2.0.0-dev.4
homepage: https://github.com/darwin-morocho/flutter-facebook-auth/tree/master/facebook_auth_desktop

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  flutter_secure_storage: ^9.0.0
  flutter_facebook_auth_platform_interface: ^6.0.0-dev.4

  # flutter_facebook_auth_platform_interface:
  #   path: ../facebook_auth_platform_interface
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    implements: flutter_facebook_auth
    platforms:
      macos:
        pluginClass: FacebookAuthDesktopPlugin
        dartPluginClass: FacebookAuthDesktopPlugin